repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: ruff
        language: python
        additional_dependencies: ["ruff==0.14.2"]
        types: [python]
        args: ["format"]
      - id: ruff-check
        name: ruff check
        entry: ruff
        language: python
        additional_dependencies: ["ruff==0.14.2"]
        types: [python]
        args: ["check"]
        require_serial: true
